### ISSUE TITLE
Multi-day event span

### ISSUE THREAD

**Issue by ghost** [eboominathan/Basic-Crud-in-Full-Calendar-Using-Codeigniter-3.0.3#1]
I would just like to ask if you could update it to having a "span", I have tried doing it for about 3 hours and I still haven't succeeded with the code. The span would provide both the start and end date. I think the most suitable callback to be used is "select" as it includes both the start and end dates. Thank you! 

It would most likely look like this: 
![span](https://cloud.githubusercontent.com/assets/16434870/12003933/1671e36a-ab6f-11e5-9281-9bcc8e98a57a.png)

**Comment by eboominathan** [comment]
i just made for single date CRUD , May be in next full calendar crud  will have start date & Start time by using select function in fullcalendar

**Comment by eboominathan** [comment]
Now Multi Day Span is updated you can check ! :+1:
