### ISSUE TITLE
npm installation error on windows

### ISSUE THREAD

**Issue by ashrashaikh** [eboominathan/Basic-Crud-in-Full-Calendar-Using-Codeigniter-3.0.3#3]
Error:-
C:>npm install cordova
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs
\node_modules\npm\bin\npm-cli.js" "install" "cordova"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! syscall getaddrinfo

npm ERR! getaddrinfo EAI_AGAIN
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\npm-debug.log

Debug log:-
0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'npm' ]
2 info using npm@2.11.2
3 info using node@v0.12.5
4 verbose install initial load of C:\Program Files\nodejs\package.json
5 verbose installManyTop reading scoped package data from C:\Program Files\nodejs\node_modules\npm\package.json
6 verbose readDependencies loading dependencies from C:\Program Files\nodejs\package.json
7 verbose install npm is installed as 2.11.2
8 silly cache add args [ 'npm', null ]
9 verbose cache add spec npm
10 silly cache add parsed spec { raw: 'npm',
10 silly cache add   scope: null,
10 silly cache add   name: null,
10 silly cache add   rawSpec: 'npm',
10 silly cache add   spec: 'C:\Program Files\nodejs\npm',
10 silly cache add   type: 'local' }
11 silly addLocalTarball shasum (computed) 0fa532e896cc4d8c877453527df2796487f40399
12 verbose addTmpTarball C:\Program Files\nodejs\npm not in flight; adding
13 verbose getCacheStat cache creation not in flight; initializing
14 verbose makeCacheDir UID & GID are irrelevant on win32
15 verbose addTmpTarball validating metadata from C:\Program Files\nodejs\npm
16 verbose tar unpack C:\Program Files\nodejs\npm
17 verbose tar unpacking to C:\Users\680547\AppData\Local\Temp\npm-4756-f36bb106\unpack-9d64e37bb7ca
18 silly gentlyRm C:\Users\680547\AppData\Local\Temp\npm-4756-f36bb106\unpack-9d64e37bb7ca is being purged
19 verbose gentlyRm don't care about contents; nuking C:\Users\680547\AppData\Local\Temp\npm-4756-f36bb106\unpack-9d64e37bb7ca
20 silly gunzTarPerm modes [ '777', '666' ]
21 error not a package C:\Program Files\nodejs\npm
22 error addLocal Could not install C:\Program Files\nodejs\npm
23 verbose stack Error: ENOENT, open 'C:\Users\680547\AppData\Local\Temp\npm-4756-f36bb106\unpack-9d64e37bb7ca\package.json'
23 verbose stack     at Error (native)
24 verbose cwd C:\Program Files\nodejs
25 error Windows_NT 6.1.7601
26 error argv "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "npm"
27 error node v0.12.5
28 error npm  v2.11.2
29 error path C:\Users\680547\AppData\Local\Temp\npm-4756-f36bb106\unpack-9d64e37bb7ca\package.json
30 error code ENOENT
31 error errno -4058
32 error enoent ENOENT, open 'C:\Users\680547\AppData\Local\Temp\npm-4756-f36bb106\unpack-9d64e37bb7ca\package.json'
32 error enoent This is most likely not a problem with npm itself
32 error enoent and is related to npm not being able to find a file.
33 verbose exit [ -4058, true ]

**Comment by eboominathan** [comment]
why are you commenting this error here ??
